# This script invokes the may-2020 DDA PIF script to compute the top 50% of scans.

from imMQExplorer.pif import PIFOverlapCalculations
import argparse
import pandas as pd

parser = argparse.ArgumentParser(description='calculates PIF')

parser.add_argument('expr', help='.d experiment file')
parser.add_argument('metaData', help='.pkl metaData file generated by fetchIsolationWIndowFeatureMapping.py')
parser.add_argument('fOut', help='name of resulting .pkl file to produce with pif data')

args = parser.parse_args()

metaData = pd.read_pickle(args.metaData)
pifObj = PIFOverlapCalculations(args.expr, metaData)

#do the pif calculations 
pifObj.calcPIF()

pifObj.savePIFMeta(args.fOut)

